version: "3.7"

services:

  assessment_a7_reactjs:
    build:
      context: ../../.
      dockerfile: Dockerfile
    command: /bin/sh -c "npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../../.:/app
      - /app/node_modules
    env_file:
      - docker.env
    ports:
      - "${REACTJS_PORT}:${REACTJS_PORT}"